version: '2'
services:
    worker:
        build:
            context: .
            dockerfile: ./docker/worker/dockerfile
        volumes:
            - .:/app
        environment:
            CELERY_BROKER: 'redis://redis_db:6379/0'
            CELERY_BACKEND: 'redis://redis_db:6379/0'
        depends_on:
            - redis_db

    flower:
        build:
            context: .
            dockerfile: ./docker/flower/dockerfile
        volumes:
            - .:/app
        ports:
            - "5555:5555"
        environment:
            BROKER: 'redis://redis_db:6379/0'
            USERNAME: admin
            PASSWORD: admin
            PRJNAME: test_celery
        depends_on:
            - redis_db
            - worker
    
    redis_db:
        image: redis
        ports:
            - "6370:6379"