version: '2'
services:
    worker:
        build:
            context: .
            dockerfile: ./docker/worker/dockerfile
        volumes:
            - .:/app
        depends_on:
            - redis
    
    flower:
        build:
            context: .
            dockerfile: ./docker/flower/dockerfile
        ports:
            - "5555:5555"
        environment:
            BROKER: 'redis://redis_db:6379/0'
            USERNAME: admin
            PASSWORD: admin
        depends_on:
            - redis
    
    redis_db:
        image: redis
        ports:
            - "6379:6379"