version: '2'
services:
    worker:
        build:
            context: ./docker/worker/
            dockerfile: dockerfile
        volumes:
            - .:/app
    
    flower:
        build:
            context: ./docker/flower/
            dockerfile: dockerfile
        ports:
            - "5555:5555"
