FROM python:2.7
RUN mkdir /app
ADD ./docker/flower/requirements.txt /app/requirements.txt
WORKDIR /app/
RUN pip install -r requirements.txt
ENV BROKER=""
ENV USERNAME=""
ENV PASSWORD=""
ENTRYPOINT celery flower --broker=${BROKER} --basic_auth=${USERNAME}:${PASSWORD}
#ENTRYPOINT ['celery','-A','test_celery', 'worker', '--loglevel=info']
